default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.9"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.21.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"]

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      language: system
      types: [python]
      entry: uv run mypy

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.3.0"
    hooks:
      - id: djade
        args: [--target-version, "5.1"]
